server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456

mybatis:
    mapperLocations: classpath:mapper/*.xml
    type-aliases-package: com.ntuzy.springcloud.entities


eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
      instance-id: payment8001
      prefer-ip-address: true
      # Eureka 客户端向服务端发送心跳的间隔时间 单位为妙（默认30妙）
      lease-renewal-interval-in-seconds: 1
      # Eureka服务端在收到最后一次心跳后等待时间上限 默认90秒 超时剔除服务
      lease-expiration-duration-in-seconds: 2

